package com.example.marketplace.enums;

public enum CareService {
    HOMEWORK_HELP,
    EVENTS,
    SHOPPING_RUNS,
    TRACKING_CHILD_DEVELOPMENT,
    TOILET_TRAINING,
    PET_CARE,
    PRAY_WITH_CHILD,
    PRAY_WITH_FAMILY,
    FEEDING_CHILD,
    FAMILY_PRAYER,
    READING_BIBLE_STORIES,
    READ_BEDTIME_STORIES,
    POTTY_TRAINING,
    TRAVEL_WITH_FAMILY,
    TAKE_CHILDREN_TO_SCHOOL,
    PICK_CHILDREN_FROM_SCHOOL,
    TAKE_CHILDREN_FOR_EVENTS,
    TAKE_CHILDREN_TO_PARK,
    EDUCATIONAL_PLAY,
    TAKE_CHILDREN_TO_CLINICS
}
